name = "arg_parser"
description = "CLI Argument Parser"
version = "0.1.0-dev"

authors = ["T. Kurt Bond"]
maintainers = ["T. Kurt Bond <tkurtbond@gmail.com>"]
maintainers-logins = ["tkurtbond"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
website = ""
tags = ["cli"]

[build-switches]
# "*".style_checks = ["-gnatyM132"]
"*".style_checks = ["-gnatwa"  # Enable all warnings
                   ,"-gnatwK"  # Don't warn about things that could be constant.
                   ,"-gnatw.X" # Disable warnings for No_Exception_Propagation
                   ,"-gnatVa" # All validity checks
                   ,"-gnaty3" # Specify indentation level of 3
                   ,"-gnatya" # Check attribute casing
                   ,"-gnatyA" # Use of array index numbers in array attributes
                   ,"-gnatyB" # Check Boolean operators
                   ,"-gnatyb" # Blanks not allowed at statement end
                   ,"-gnatyc" # Check comments
                   ,"-gnaty-d" # Disable check no DOS line terminators present
                   ,"-gnatye" # Check end/exit labels
                   ,"-gnatyf" # No form feeds or vertical tabs
                   ,"-gnatyh" # No horizontal tabs
                   ,"-gnatyi" # Check if-then layout
                   ,"-gnatyI" # check mode IN keywords
                   ,"-gnatyk" # Check keyword casing
                   ,"-gnatyl" # Check layout
                   ,"-gnatym" # Check maximum line length
                   ,"-gnatyM132" # 132 characters maximum.
                   ,"-gnatyn" # Check casing of entities in Standard
                   ,"-gnatyO" # Check that overriding subprograms are explicitly marked as such
                   ,"-gnatyp" # Check pragma casing
                   ,"-gnatyr" # Check identifier references casing
                   ,"-gnatyS" # Check no statements after THEN/ELSE
                   ,"-gnatyt" # Check token spacing
                   ,"-gnatyu" # Check unnecessary blank lines
                   ,"-gnatyx" # Check extra parentheses
                   ]
